In [30]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np
import pandas as pd
path="/content/drive/MyDrive/Colab Notebooks/DATA WRANGLING.csv"
dd=pd.read_csv(path)
print(dd.head(5))

In [ ]:
print(dd.dtypes)
print(dd.describe())

In [ ]:
dd.isna().sum()

In [35]:
mean_age = dd['Age'].mean()
dd['Age'].fillna(mean_age, inplace=True)

In [ ]:
dd.isna().sum()

In [ ]:
dd.drop(columns=['Cabin'], axis=1, inplace=True)
print(dd.head(5))

In [ ]:
passengers_over_40 = dd[dd['Age'] > 40]
passengers_over_40[['Name', 'Age']]

In [49]:
merged_rows = pd.concat([dd.head(2), dd.tail(2)])
merged_rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q